version: "3"

tasks:
  test:
    cmds:
      - go test -v -coverprofile=coverage.out ./...

  show-cover:
    cmds:
      - dokimi report --input=coverage.out --output=coverage.json --reporter=istanbul --show

  build:
    cmds:
      - go build -o ./bin/dokimi github.com/farbodsalimi/dokimi

  build-all:
    cmds:
      - ./scripts/build-all.sh github.com/farbodsalimi/dokimi

  default:
    cmds:
      - go build ./...
    silent: true
