name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v

      - name: Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 7442645f3d316d873958dd124e244c15cef0e7a11b1506f68932a04e472b58b5
        with:
          prefix: github.com/farbodsalimi/dokimi
          coverageCommand: go test -v --race -covermode=atomic -coverprofile=coverage.out ./...
          coverageLocations: ${{github.workspace}}/coverage.out:gocov
